// Let's write the main fucnction

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lex.yy.c" /*This file will be generated by the lex*/

typedef struct node
{
    char *name;
    struct node *next;
} node;

typedef node *symbolTable;

// To add the identifier in the symbol Table

symbolTable addtbl(symbolTable T, char *id)
{
    symbolTable temp = T;
    while (temp)
    {
        if (!strcmp(temp->name, id))
        {
            printf("Id:{%s} is already present\n", id);
            exit(0);
        }
        temp = temp->next;
    }
    // else add it to the front of the linked list
    temp = (symbolTable)malloc(sizeof(node));
    temp->name = (char *)malloc(strlen(id) + 1);
    strcpy(temp->name, id);
    temp->next = T;
    T = temp;
    // print the message
    printf("Id:{%s} is added to the Symbol Table\n", id);
    return T;
}

// print symbolTable for the identifiers
void print(symbolTable T)
{
    printf("*****************SymbolTable*****************\n");
    symbolTable temp = T;
    while (temp)
    {
        printf("ID : %s\n", temp->name);
        temp = temp->next;
    }
    printf("\n");
}

int main()
{
    int nextToken;
    symbolTable T = NULL;
    while ((nextToken = yylex()))
    {
        switch (nextToken)
        {
        case KEYWORDS:
            printf("KEYWORDS: %s\n", yytext);
            break;
        case IDENTIFIER:
            // add the identifier to the symbol Table
            T = addtbl(T, yytext);
            printf("Idnetifiers: %s\n", yytext);
            break;
        case INTEGER_CONST:
            printf("Integer constants: %s\n", yytext);
            break;
        case FLOAT_CONST:
            printf("Floating constants: %s\n", yytext);
            break;
        case ENUM_CONST:
            printf("Enum constants: %s\n", yytext);
            break;
        case CHAR_CONST:
            printf("char constant: %s\n", yytext);
            break;
        case STRING_LITERAL:
            printf("string literal: %s\n", yytext);
            break;
        case PUNCTUATOR:
            printf("punctuators: %s\n", yytext);
            break;
        case MULTI_COM:
            printf("Multi line comment\n");
            break;
        case SINGLE_COM:
            printf("Single line comment\n");
            break;
        default:
            printf("Other\n");
            break;
        }
    }

    printf("\n");
    print(T);
    return 0;
}
