// Let's write the main fucnction

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lex.yy.c" /*This file will be generated by the lex*/

typedef struct node
{
	char *name;
	struct node *next;
} node;

typedef node *symbolTable;

// To add the identifier in the symbol Table

symbolTable addtbl(symbolTable T, char *id)
{
	symbolTable temp = T;
	while (temp)
	{
		if (!strcmp(temp->name, id))
		{
			printf("Id:{%s} is already present\n", id);
			exit(0);
		}
		temp = temp->next;
	}
	// else add it to the front of the linked list
	temp = (symbolTable)malloc(sizeof(node));
	temp->name = (char *)malloc(strlen(id) + 1);
	strcpy(temp->name, id);
	temp->next = T;
	T = temp;
	// print the message
	printf("Id:{%s} is added to the Symbol Table\n", id);
	return T;
}

int main()
{
	int nextToken;
	symbolTable T = NULL;
	while ((nextToken = yylex()))
	{
		switch (nextToken)
		{
		case ASG:
			printf("Assignment\n");
			break;
		case ID:
			T = addtbl(T, yytext);
			break;
		case NUM:
			printf("Number: %s\n", yytext);
			break;
		case LP:
			printf("Beginning of Left Parenthesis\n");
			break;
		case RP:
			printf("Beginning of Right parenthesis\n");
			break;
		case IF:
			printf("If statement\n");
			break;
		case ELSE:
			printf("Else statement\n");
			break;
		case EQ:
			printf("Equal Opearator\n");
			break;
		case NE:
			printf("Not equal to Operator\n");
			break;
		case GT:
			printf("Greater than\n");
			break;
		case GE:
			printf("Greater than Equal to\n");
			break;
		case LT:
			printf("Less than\n");
			break;
		case LE:
			printf("Less than Equal to\n");
			break;
		default:
			printf("Other\n");
			break;
		}
	}
	return 0;
}
